src/Entity/Booking.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ad", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\GreaterThan("today", message="La date d'arrivée ne peut pas être avant ce jour !", groups={"front"})
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\GreaterThan(propertyPath="startDate", message="La date de départ ne peut pas être avant la date d'arrivée !")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * Callback appelé à chaqu fois qu'on créer une réservatoion
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * 
     * @return void
     */
    public function prePersist()
    {
        if (empty($this->createdAt)) {
            $this->createdAt = new \DateTime();
        }

        if (empty($this->amount)) {
            //prix de l'annonce par le nombre de jours
            $this->amount = $this->ad->getPrice() * $this->getDuration();
        }
    }

    /**
     * Fonction qui retourne True ou False si les dates choisies sont dispo à la réservation
     *
     * @return boolean
     */
    public function isBookableDates()
    {
        // 1 Il faut connaitre les date impossible pour l'annonce
        $notAvailableDays = $this->ad->getNotAvailableDays();
        // 2 Il faut comparer les dates choisies avec les dates impossibles
        $bookingDays = $this->getDays();

        //Function qui format les dates 
        $formatDay = function ($day) {
            return $day->format('Y-m-d');
        };

        // $days = Tableau des chaines de caractères de mes journées de location en utilisant la fonction $formatday crée plus haut
        $days           = array_map($formatDay, $bookingDays);
        $notAvailable   = array_map($formatDay, $notAvailableDays);

        // Parcours les jours et regarde si ils ne sont pas dans le tableau des date déjà réservée et return false si les dates y sont
        foreach ($days as $day) {
            if (array_search($day, $notAvailable) !== false) return false;
        }

        return true;
    }

    /**
     * Permet de récupérer un tableau des jours de la réservation 
     *
     * @return array Un tableau d'objets DateTime représentant les jours de la réservation
     */
    public function getDays()
    {
        $resultat = range(
            $this->startDate->getTimestamp(),
            $this->endDate->getTimestamp(),
            24 * 60 * 60
        );

        $days = array_map(function ($dayTimestamp) {
            return new \DateTime(date('Y-m-d', $dayTimestamp));
        }, $resultat);

        return $days;
    }


    public function getDuration()
    {
        $diff = $this->endDate->diff($this->startDate);
        return $diff->days;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *  fields={"email"},
 *  message="Un autre utilisateur possède déjà cet email, merci de le changer!"
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @assert\NotBlank(message="Le nom est obligatoire !")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @assert\NotBlank(message="Le prénom est obligatoire !")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @assert\Email(message="Cet email n'est pas valide !")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @assert\Url(message="Veuillez donner une url valde !")
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;

    /**
     * @assert\EqualTo(propertyPath="hash", message="Vous n'avez pas rentrer exactemetn le même mot de passe !")
     */
    public $passwordConfirm;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $introduction;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ad", mappedBy="author")
     */
    private $ads;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Role", mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="booker")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="author", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\AdLike", mappedBy="user")
     */
    private $likes;

    /**
     * Permet de retourner le nom et le prénom
     * @return string 
     */
    public function getFullName()
    {
        return "{$this->firstName} {$this->lastName}";
    }


    /**
     * Permet d'initialiser un slug d'après le titre soit lors de la création soit lors de la mise à jour
     * 
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * 
     * @return void
     */
    public function creationSlug()
    {
        if (empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstName . ' ' . $this->lastName);
        }
    }


    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->likes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(?string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->contains($ad)) {
            $this->ads->removeElement($ad);
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    public function getRoles()
    {
        $roles = $this->userRoles->map(function ($role) {
            return $role->getTitle();
        })->toArray();

        $roles[] = 'ROLE_USER';

        return $roles;
    }

    public function getPassword()
    {
        return $this->hash;
    }

    public function getSalt()
    {
    }

    public function getUsername()
    {
        return $this->email;
    }

    public function eraseCredentials()
    {
    }

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->contains($userRole)) {
            $this->userRoles->removeElement($userRole);
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|AdLike[]
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(AdLike $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes[] = $like;
            $like->setUser($this);
        }

        return $this;
    }

    public function removeLike(AdLike $like): self
    {
        if ($this->likes->contains($like)) {
            $this->likes->removeElement($like);
            // set the owning side to null (unless already changed)
            if ($like->getUser() === $this) {
                $like->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Entity\Comment;
use App\Form\BookingType;
use App\Form\CommentType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BookingController extends AbstractController
{
    /**
     * @Route("/ads/{slug}/book", name="booking_create")
     * @IsGranted("ROLE_USER")
     */
    public function book(Ad $ad, Request $request, EntityManagerInterface $manager)
    {
        $booking = new Booking();
        $form = $this->createForm(BookingType::class, $booking);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user = $this->getUser();

            $booking->setBooker($user)
                ->setAd($ad);

            //Si les dates ne sont pas dispo = message d'erreur
            if (!$booking->isBookableDates()) {
                $this->addFlash(
                    'warning',
                    "Les dates qui vous avez choisi ne peuvent pas être réservées : elles sont déjà prises."
                );
            } else {

                $manager->persist($booking);
                $manager->flush();

                return $this->redirectToRoute('booking_show', ['id' => $booking->getId(), 'withAlert' => true]);
            }
        }

        return $this->render('booking/book.html.twig', [
            'ad' => $ad,
            'form' => $form->createView(),
        ]);
    }

    /**
     * Permet d'afficher la page d'une réservation
     * @Route("/booking/{id}", name="booking_show")
     * @IsGranted("ROLE_USER")
     * 
     * @param Booking $booking
     * @param Request $request
     * @param EntityManagerInterface $manager
     * @return Response
     */
    public function show(Booking $booking, Request $request, EntityManagerInterface $manager)
    {
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user = $this->getUser();

            $comment->setAuthor($this->getUser())
                ->setAd($booking->getAd());

            $manager->persist($comment);
            $manager->flush();

            $this->addFlash(
                'success',
                "Merci! Votre avis a bien été enregistré."
            );
        };

        return $this->render('booking/show.html.twig', [
            'booking'   => $booking,
            'form'      => $form->createView()
        ]);
    }
}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réserver l'annonce: {{ad.title}}{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha256-siyOpF/pBWUPgIcQi17TLBkjvNgNQArcmwJB8YvkAgg=" crossorigin="anonymous" />

{% endblock %}

{% block body %}
<div class="container">
    <h2><small>Réserver pour l'annonce: </small><strong>{{ad.title}}</strong></h2>
    <p>Vous êtes sur le point de réserver l'annonce de <strong>{{ad.author.fullname}}</strong>, dites nous tout on s'occupe du reste !</p>

    {{form_start(form)}}
        <div class="alert alert-light p-5">
            <h4 class="mb-3">Commencez par nous dire quelles sont les dates qui vous intéressent !</h2>
            <div class="row">
                <div class="col-md">
                    {{form_row(form.startDate)}}
                </div>
                <div class="col-md">
                    {{form_row(form.endDate)}}
                </div>
            </div>
        
        <h5 class="mb-5">Montant estimez de votre séjour: <strong><span id="amount"></span> CHF</strong> pour <span id="days"> 0</span> nuit(s) à {{ad.price | number_format(2, ',', ' ')}} CHF/Nuit</h5>
    
        {{form_row(form.comment)}}
        <button type="submit" class="btn btn-success">Reserver</button>
        </div>
    {{form_end(form)}}
    
</div>
{% endblock %}

{% block javascripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>

<script>
    $(document).ready(function(){
        $('#booking_startDate, #booking_endDate').datepicker({
            format: 'dd.mm.yyyy',
            datesDisabled: [
                {% for day in ad.notAvailableDays %}
                    '{{ day.format('d.m.Y') }}',
                {% endfor %}
            ],
            startDate: new Date()
        });
        $('#booking_startDate, #booking_endDate').on('change', calculateAmount);
    });
    function calculateAmount() {
        // On chope les dates
        const endDate = new Date(
            $('#booking_endDate')
                .val()
                .replace(/(\d+).(\d+).(\d{4})/, '$3-$2-$1')
        );
        
        const startDate = new Date(
            $('#booking_startDate')
                .val()
                .replace(/(\d+).(\d+).(\d{4})/, '$3-$2-$1')
        );
        if(startDate && endDate && startDate < endDate){
            const DAY_TIME  = 24 * 60 * 60 * 1000;
            const interval  = endDate.getTime() - startDate.getTime();
            const days      = interval / DAY_TIME;
            const amount    = days * {{ ad.price }};
            $('#days').text(days);
            $('#amount').text(amount.toLocaleString('fr-CH'));
        }
    }

</script>

{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail de la réservation: {{booking.id}}{% endblock %}

{% block body %}

    {% set ad = booking.ad %}
    {% set author = ad.author %}

    <div class="container">
        <h2 class="my-5">Votre réservation (N°{{booking.id}})</h2>
        {% if app.request.query.get('withAlert') %}
            <div class="alert alert-success">
                <h4>Bravo!</h4>
                <p>Votre réservation auprès de <strong><a href="{{path('user_show',{'slug': author.slug} )}}">{{author.fullName}}</a></strong> pour l'annonce <strong><a href="{{path('ads_show', {'slug': ad.slug})}}">{{ad.title}}</a></strong> à bien été enregistrée. </p>
            </div>
        {% endif %}
        <div class="row mt-4">
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h4>Détails</h4>
                        <dl class="raw">
                            <dt class="col-md-4">Numéro</dt>
                            <dd class="col-md-8">{{booking.id}}</dd>
                            <dt class="col-md-4">Date d'arrivée</dt>
                            <dd class="col-md-8">{{booking.startDate | date('d.m.Y')}}</dd>
                            <dt class="col-md-4">Date de départ</dt>
                            <dd class="col-md-8">{{booking.endDate | date('d.m.Y')}}</dd>
                            <dt class="col-md-4">Nombre de nuits</dt>
                            <dd class="col-md-8">{{booking.duration}}</dd>
                            <dt class="col-md-4">Montant total</dt>
                            <dd class="col-md-8">{{booking.amount | number_format(2, ',', ' ')}} CHF</dd>
                            <dt class="col-md-4">Commentaire</dt>
                            <dd class="col-md-8">{{booking.comment | default('Aucun commentaire')}}</dd>
                        </dl>
                        <hr>
                        <h4 class="alert-heading">Votre hôte</h4>
                        <div class="row mt-3">
                            <div class="col-2">
                                <img src="{{author.picture}}" class="avatar avatar-medium" alt="l'avatar de {{author.fullName}}">
                            </div>
                            <div class="col">
                                <h5><a href="{{path('user_show',{'slug': author.slug} )}}">{{author.fullName}}</a></h5>
                                <span class="badge badge-pill badge-info">{{ author.ads | length}} Annonces</span>
                            </div>
                        </div>
                        <div class="mt-3">{{author.description|raw}}</div>
                        <a href="{{path('user_show',{'slug': author.slug} )}}" class="btn btn-primary">Voir le profile de {{author.firstName}}</a>
                    </div>
                </div>
                <div class="alert alert-light mt-4">
                    
                    {% if date() > date(booking.endDate) %}
                        {% set comment = booking.ad.CommentFromAuthor(app.user) %}
                        {% if comment is not null %}
                            <h4 class="alert-heading">Votre avis: </h4>
                            <blockquote>
                                {{comment.content}}
                            </blockquote>
                            <strong>Note: {% include "partials/rating.html.twig" with {'rating': comment.rating} %}</strong>
                        {% else %}
                            <h4 class="alert-heading">Votre avis compte !</h4>
                            {{ form_start(form) }}
                            {{ form_widget(form) }}
                            <button type="submit" class="btn btn-success">Confirmer !</button>
                            {{ form_end(form)}}
                        {% endif %}
                    {% else %}
                        <p>Vous ne pourrez pas noté cette annonce tant que votre séjour ne se sera pas terminé !</p>
                    {% endif %}
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h4 class="alert-heading mb-3">Votre hébergement</h4>
                        <h4>
                            <a href="{{path('ads_show', {'slug': ad.slug})}}">{{ad.title}}</a>
                        </h4>
                        <img src="{{ad.coverImage}}" alt="Image de {{ad.title}}" class="img-fluid rounded mt-4 mb-4">
                        {{ad.content|raw}}
                        <a href="{{path('ads_show', {'slug': ad.slug})}}" class="btn btn-primary">Plus d'informations</a>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}