src/Entity/Ad.php
<?php

namespace App\Entity;

use App\Entity\User;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints\DateTime;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


/**
 * @ORM\Entity(repositoryClass="App\Repository\AdRepository")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 *  fields={"title"},
 *  message="Une autre annonce possède déjà le même titre, merci de le modifier!"
 * )
 */
class Ad
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @assert\length(min=10, max=255, minMessage="Le titre doit contenir 10 caractéres au minimum", maxMessage="Le titre ne peut pas contenir plus de 255 caractères")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     * @assert\length(min=20, minMessage="L'introduction doit contenir 20 caractéres au minimum")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @assert\length(min=100, minMessage="L'introduction doit contenir 100 caractéres au minimum")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     * @assert\url()
     */
    private $coverImage;

    /**
     * @ORM\Column(type="integer")
     * 
     */
    private $rooms;

    /**
     * Ce champs est liés a l'entité image
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="ad", orphanRemoval=true)
     * Ci-dessous je force symfony a valider égalment le sous-formulaire image 
     * @assert\Valid()
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="ad")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="ad", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\AdLike", mappedBy="ad")
     */
    private $likes;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->likes = new ArrayCollection();
    }

    /**
     * Permet d'initialiser un slug d'après le titre soit lors de la création soit lors de la mise à jour
     * 
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * 
     * @return void
     */
    public function creationSlug(){
        if(empty($this->slug)){
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }
    }

    /**
     * Fonction qui récupère le commentaire de l'auteur par rapport a une annonce
     *
     * @param User $author
     * @return void
     */
    public function getCommentFromAuthor(User $author){
        foreach ($this->comments as $comment) {
            if($comment->getAuthor() === $author) return $comment;
        }

        return null;
    }  

    /**
     * Permet de retourner la moyenne des notes d'une annonce
     *
     * @return float
     */
    public function getAvgRatings(){
        //calculler la somme des notations
        $sum = array_reduce($this->comments->toArray(), function($total, $comment){
            return $total + $comment->getRating();
        }, 0);
        //calculler la moyenne
        if(count($this->comments) > 0) return $sum / count($this->comments);

        return 0;
    }

    /**
     * Permet d'obtenir un tableau des jours qui ne sont pas disponibles pour cette annonce
     *
     * @return array Un tableau d'objets DateTime représentant les jours d'occupation 
     */
    public function getNotAvailableDays()
    {
        // On récupère les réservation
        $notAvailableDays = [];

        foreach($this->bookings as $booking) {
            // calculer les jours qui se trouve entre la date d'arrivée et de départ et on le met dans un tableau
            $resultat = range(
            $booking->getStartDate()->getTimestamp(), //Je récupère le timestamp de la date de début
            $booking->getEndDate()->getTimestamp(),   //Je récupère le timestamp de la date de fin
            24 * 60 * 60 );                    //On transforme une journée en timestamp

            //On transforme chaques timestamp du tableau $resultat et on le transforme en date
            $days = array_map(function($dayTimestamp) {
                return new \DateTime(date('Y-m-d', $dayTimestamp));
            }, $resultat);

            $notAvailableDays = array_merge($notAvailableDays, $days);
        }

        return $notAvailableDays;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection|AdLike[]
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(AdLike $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes[] = $like;
            $like->setAd($this);
        }

        return $this;
    }

    public function removeLike(AdLike $like): self
    {
        if ($this->likes->contains($like)) {
            $this->likes->removeElement($like);
            // set the owning side to null (unless already changed)
            if ($like->getAd() === $this) {
                $like->setAd(null);

src/Controller/AdController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\AdLike;
use App\Form\AdType;
use App\Repository\AdLikeRepository;
use App\Repository\AdRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class AdController extends AbstractController
{
    /**
     * @Route("/ads", name="ads_index")
     */
    public function index(AdRepository $repo)
    {
        $ads = $repo->findAll();

        return $this->render('ad/index.html.twig', [
            'ads' => $ads
        ]);
    }

    /**
     * Controller qui Permet de créer une annonce via un formulaire
     * 
     * @Route("/ads/new", name="ads_create")
     * @IsGranted("ROLE_USER")
     * 
     * @return Response
     */
    public function create(Request $request, EntityManagerInterface $manager )
    {
        
        //On crée un nouvel objet Ad
        $ad = new Ad();
        //On crée un formulaire avec la fonction createForm et on lui passe la classe AdType et notre nouvel objet $ad
        $form  = $this->createForm(AdType::class, $ad);
        //Fonction qui permet de faie le lien entre les paramètre rentrés en requête et l'objet Ad
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
        //pour chaques image du slider on ajoute les images à l'entité image avec l'id de l'annonce
            foreach($ad->getImages() as $image) { 
                $image->setAd($ad);
                $manager->persist($image);
            }

            $ad->setAuthor($this->getUser());
        
            $manager->persist($ad);
            $manager->flush();
            
            //On créer un message flash pour informer l'utilisateur que l'envoi a bien fonctionné
            $this->addFlash(
                'success',
                "L'annonce <strong>{$ad->getTitle()}</strong> a bien été enregistrée!"
            );

            //Redirection après la création de l'annonce
            return $this->redirectToRoute('ads_show',[
                'slug' => $ad->getSlug()
            ]);
        }

        return $this->render('ad/new.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * Permet d'éditer une annonce grace au paramConverter passé dans les paramêtre de la fonction
     * 
     * @Route("/ads/{slug}/edit", name="ads_edit")
     * @Security("is_granted('ROLE_USER') and user === ad.getAuthor()", message="Cette annonce ne vous appartient pas, vous ne pouvez pas la modifier")
     *
     * @return Response
     */
    public function edit(Ad $ad, Request $request, EntityManagerInterface $manager  ){

        $form  = $this->createForm(AdType::class, $ad);
        //Fonction qui permet de faie le lien entre les paramêtre rentrés en requête et l'objet Ad
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            //pour chaques image du slider on ajoute les images à l'entité image avec l'id de l'annonce
                foreach($ad->getImages() as $image) { 
                    $image->setAd($ad);
                    $manager->persist($image);
                }
            
                $manager->persist($ad);
                $manager->flush();
                
                //On créer un message flash pour informer l'utilisateur que l'envoi a bien fonctionné
                $this->addFlash(
                    'success',
                    "L'annonce <strong>{$ad->getTitle()}</strong> a bien été mise à jour!"
                );
    
                //Redirection après la création de l'annonce
                return $this->redirectToRoute('ads_show',[
                    'slug' => $ad->getSlug()
                ]);
            }

        return $this->render('ad/edit.html.twig', [
            'form' => $form->createView(),
            'ad' => $ad
        ]);
    }

    /**
     * Permet de supprimer une annonces
     * 
     * @Route("/ads/{slug}/delete", name="ads_delete")
     * @Security("is_granted('ROLE_USER') and user === ad.getAuthor()", message="Cette annonce ne vous appartient pas, vous ne pouvez pas la supprimer")
     * 
     * @param Ad $ad
     * @param ObjectManager $manger
     * @return Response
     */
    public function delete(Ad $ad, EntityManagerInterface $manager)
    {
        $manager->remove($ad);
        $manager->flush();

        $this->addFlash(
            'success',
            "L'annonce <strong>{$ad->getTitle()}</strong> a bien été supprimée!"
        );

        return $this->redirectToRoute("ads_index");
    }

    /**
     * Permet d'afficher une seule annonce grace au paramConverter passé dans les paramêtre de la fonction
     * 
     * @Route("/ads/{slug}", name="ads_show")
     *
     * @return Response
     */
    public function show(Ad $ad)
    {
        return $this->render('ad/show.html.twig', [
            'ad' => $ad
        ]);
    }

    /**
     * Permet de liker ou unliker une annonce
     * 
     * @Route("/ads/{slug}/like", name="ad_like")
     * 
     * @param Ad $ad 
     * @param EntityManagerInterface $manager 
     * @param AdLikeRepository $likeRepo 
     * @return Response 
     */
    public function like(Ad $ad, EntityManagerInterface $manager, AdLikeRepository $likeRepo) : Response
    {
        $user = $this->getUser();

        if (!$user) return $this->json([
            'code' => 403,
            'message' => "Unauthorized"
        ], 403);

        if ($ad->isLikedByUser($user)) {
            $like = $likeRepo->findOneBy([
                'ad' => $ad,
                'user' => $user
            ]);

            $manager->remove($like);
            $manager->flush();

            return $this->json([
                'code' => 200,
                'message' => "Like bien supprimé",
                'likes' => $likeRepo->count(['ad' => $ad])
            ], 200);
        }
        $like = new AdLike();
        $like   ->setAd($ad)
                ->setUser($user);

        $manager->persist($like);
        $manager->flush();

        return $this->json([
            'code' => 200, 
            'message' => 'Like bien ajouté',
            'likes' => $likeRepo->count(['ad' => $ad])
        ], 200);

    }

}

templates/ad/_ad.html.twig
    {% set url = path('ads_show', {'slug': ad.slug}) %}
    <div class="col-md-4">
        <div class="card bg-light mb-3">
            <div class="card-header text-center">
                {{ ad.rooms }} Chambres, <strong>{{ ad.price | number_format(2, ',', ' ') }} CHF / nuit</strong><br>
                <small>
                    {% if ad.comments|length > 0 %}
                    {% set rating = ad.comments|length  %}
                    {% include "partials/rating.html.twig" with {'rating': ad.avgRatings} %}
                        ({{ad.comments|length}} avis)
                    {% else %}
                        Pas encore noté
                    {% endif %}
                </small>
            </div>
            <a href="{{ url }}">
                <img src="{{ ad.coverImage }}" alt="Image de l'appartement" style="height: 200px; width:100%; display:block;">
            </a>
            <div class="card-body">
                <a href="{{ url }}">
                    <h4 class="card-title">
                        {{ ad.title }}
                    </h4>
                </a>
                <p class="card-texte">
                    {{ ad.introduction }}
                </p>
                <a href="{{ path('ad_like', {'slug': ad.slug }) }}" class="btn btn-link float-left js-like-{{ad.slug}}">
                {% if app.user and ad.isLikedByUser(app.user) %}
                    <i class="fas fa-thumbs-up"></i>
                {% else %}
                    <i class="far fa-thumbs-up"></i>
                {% endif %}
                    <span class="js-likes">{{ad.likes | length }}</span>
                    <span class="js-label">J'aime</span>
                </a>
                <a href="{{ url }}" class="btn btn-secondary float-right">En savoir plus</a>
            </div>
        </div>
    </div>

{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

    <script>

        function onClickBtnLike(event){
            event.preventDefault();

            const url = this.href;
            const spanCount = this.querySelector('span.js-likes');
            const icone = this.querySelector('i.fa-thumbs-up');


            axios.get(url).then(function(response){
                spanCount.textContent = response.data.likes;

                if(icone.classList.contains('fas')) {
                    icone.classList.replace('fas', 'far');
                } else {
                    icone.classList.replace('far', 'fas');
                }
            }).catch(function(error){
                if(error.response.status === 403){
                    window.alert("Vous ne pouvez pas liker sans être connecter !")
                } else {
                    window.alert("Une erreur s'est produite, merci de réeseyer plus tard !")
                }
            });
        }

        document.querySelectorAll('a.js-like-{{ad.slug}}').forEach(function(link){
            link.addEventListener('click', onClickBtnLike);
        })
    </script>

{% endblock %}

templates/ad/_collection.html.twig
{% block _ad_images_widget %}
    <p>Images additionnelles pour le slider d'images:</p>
    {{form_widget(form)}}
    <input type="hidden" id="widgets-counter" value="0">
    <div class="form-group">
        <button type="button" id="add-image" class="btn btn-primary"><i class="fas fa-plus mr-1"></i> Ajouter une image</button>
    </div>
{% endblock %}

{% block _ad_images_entry_row %}
    {{form_widget(form)}}
{% endblock %}

{% block _ad_images_entry_widget %}
    <div class="form-group" id="block_{{id}}">
        <div class="row">
            <div class="col-10">
                <div class="row">
                    <div class="col">
                        {{form_widget(form.url)}}
                        {{form_errors(form.url)}}
                    </div>
                    <div class="col">
                        {{form_widget(form.caption)}}
                        {{form_errors(form.caption)}}
                    </div>
                    <div class="col-2">
                        <button type="button" data-action="delete" data-target="#block_{{id}}" class="btn btn-danger" >X</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/ad/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edition d'une annonce{% endblock %}

{% form_theme form 'ad/_collection.html.twig' %}

{% block body %}
<div class="container">
    <h1>Edition de: {{ ad.title }}</h1>
    <br>
    {{ form_start(form) }}

    {{ form_widget(form) }}
    <button type="submit" class="btn btn-primary">Enregistrer les modifications</button>

    {{ form_end(form) }}
</div>
{% endblock %}

{# Script JS qui permet de créer un formulaire d'ajout d'image pour le slider #}
{% block javascripts %}

<script src="{{ asset('build/js/ad.js') }}"></script>

{% endblock %}

templates/ad/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos magnifiques annonces{% endblock %}

{% block body %}
<div class="container">
    <h1 class="my-5">Voici les annonces de nos hôtes!</h1>
    <div class="row ads-index">
        {% for ad in ads %}
            {% include 'ad/_ad.html.twig' %}
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/ad/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Création d'une annonce{% endblock %}

{% form_theme form 'ad/_collection.html.twig' %}

{% block body %}

<div class="container">
    <h1 class="my-5">Créer une nouvelle annonce</h1>
    {{ form_start(form) }}

    <div class="row">
        <div class="col">
            <div class="alert alert-light p-4">
                <h3>Information générales</h3>
                <hr>
                {{form_row(form.title)}}
                {{form_row(form.slug)}}
                {{form_row(form.price)}}
                {{form_row(form.rooms)}}
            </div>
        </div>
        <div class="col">
            <div class="alert alert-light p-4">
                <h3>Détails de l'annonces</h3>
                <hr>
                {{form_row(form.introduction)}}
                {{form_row(form.content)}}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col my-3">
            <div class="alert alert-light">
                <h3>Images de l'annonce</h3>
                <hr>
                {{form_row(form.coverImage)}}
                {{form_row(form.images)}}
            </div>
        </div>
    </div>
    <div class="alert alert-success clearfix">
        <h3 class="alert-heading">Sauvegarder votre annonce</h3>
        <p>Super! vous êtes au bout de la création de votre annonce pour enregistrer, vous n'avez plus qu'a confirmer en cliquant sur le bouton si dessous</var></p>
        <button type="submit" class="btn btn-primary"><i class="fas fa-check mr-1"></i> Créer une annonce</button>
    </div>
    {{ form_end(form) }}

</div>

{% endblock %}

{% block javascripts %}
    <script src="{{ asset('build/js/ad.js') }}"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
{% endblock %}

templates/ad/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ad.title}}{% endblock %}

{% block body %}
    <div class="da-title" style="background-image: url({{ad.coverImage}});">
        <div class="container contentHeader"> 
            <h1>{{ad.title}}</h1>
            <p>{{ad.introduction}}</p>
            <p class="h3">
                <strong>{{ad.rooms}} chambres</strong> pour <strong>{{ad.price | number_format(2, ',', ' ')}} CHF</strong> par nuit
            </p>
            <a href="{{path('booking_create', {'slug': ad.slug})}}" class="btn btn-success">Réserver</a>
                {% if app.user and app.user == ad.author %}
                    <a href="{{path('ads_edit', {'slug': ad.slug})}}" class="btn btn-dark ml-3"><i class="fas fa-edit mr-1"></i>Modifier</a>
                    <a href="{{path('ads_delete', {'slug': ad.slug})}}" class="btn btn-danger"><i class="fas fa-trash-alt mr-1" onclick="return confirm(`Etes-vous sur de vouloir supprimer cette annonce ?`)"></i>Supprimer</a>
                {% endif %}
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 mb-3">
                {{ad.content | raw}}
                {% if ad.comments|length > 0 %}
                <div class="alert alert-info">
                    <h5 class="alert-heading">
                        <div class="row align-items-center">
                            <div class="col">Note globale donnée par nos voyageurs
                            </div>
                            <div class="col text-center">
                                {% include "partials/rating.html.twig" with {'rating': ad.avgRatings} %} <br>
                                <small>(Moyenne sur {{ ad.comments|length}} avis)</small>
                            </div>
                        </div>
                    </h5>
                </div>
                {% endif %}
                <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
                    <div class="carousel-inner">
                        {% for image in ad.images %}
                        <div class="carousel-item {% if loop.first %}active{% endif %}">
                            <img src="{{ image.url }}" class="d-block w-100" alt="...">
                            <div class="carousel-caption d-none d-md-block">
                                <h5>{{ ad.title }}</h5>
                                <p>{{ image.caption }}</p>
                            </div>
                          </div>
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="sr-only">Next</span>
                    </a>
                </div>
                <hr>
                {% if ad.comments|length > 0 %}
                <h4 class="mb-3">Commentaires de nos voyageurs</h4>
                
                {% for comment in ad.comments %}
                    <div class="bg-light rounded mb-3 py-3 px-3">
                        <strong>{{comment.author.firstName}}</strong> a dit:
                        <blockquote>
                            {{comment.content}}
                        </blockquote>
                        <strong>Note:</strong>
                        {% include "partials/rating.html.twig" with {'rating': comment.rating} %}
                    </div>
                    {% endfor %} 
                {% else %}
                    <h4>Cette annonce n'a pas encore reçu de commentaires ...</h4>
                {% endif %}
            </div>
            <div class="col">
                {% set a = ad.author %}
                <div class="row mb-3">
                    <div class="col-3">
                        <a href="{{ path('user_show',{'slug': a.slug}) }}"><img src="{{a.picture}}" class="avatar avatar-medium" alt="Avatar de {{a.fullname}}"></a>
                    </div>
                    <div class="col">
                        <h4><a href="{{ path('user_show',{'slug': a.slug}) }}">{{a.fullName}}</a></h4>
                        <span class="badge badge-pill badge-info">{{ a.ads | length}} Annonces</span>
                    </div>
                </div>
                {{a.description | raw}}
            </div>
        </div>
    </div>

{% endblock %}